fixtures:
  repositories:
    stdlib: git://github.com/puppetlabs/puppetlabs-stdlib.git
    create_resources: git://github.com/puppetlabs/puppetlabs-create_resources.git
    gpg_key: git://github.com/treydock/puppet-gpg_key.git
    epel: git://github.com/stahnma/puppet-module-epel.git
  symlinks:
    zfsonlinux: "#{source_dir}"
